### ISSUE TITLE
generate data models and relationships from existing database

### ISSUE THREAD

**Issue by sweiland** [sweiland/fhj.swenga2017.plavent#1]
possibly usable: https://www.eclipse.org/webtools/dali/docs/3.2/user_guide/tasks006.htm

**Comment by hoedlale16** [comment]
At the moment we create the database from the java-classes.

**Comment by hoedlale16** [comment]
I think we can close this feature. We will  get the innovation points with the profile picture and PDF export. 
The database is well structured and we will not implement this feature anymore.
