### ISSUE TITLE
fix chicken-egg-problem

### ISSUE THREAD

**Issue by sweiland** [sweiland/fhj.swenga2017.plavent#11]
when the application starts for the first time, there's no admin to administer the db

**Comment by hoedlale16** [comment]
Problem fixed. On initial setup/startup, the web-page
http://localhost:8080/fhj.swenga2017.plavent/preparePlavent 
needs to be called. This creates all required meta-data (categories,status-values, users) 
Administrator: admin/admin
With this user you can create your environment.
