### ISSUE TITLE
1.1.1.9. As a host, I want to see an overview of all events in the dashboard page after login

### ISSUE THREAD

**Issue by hoedlale16** [sweiland/fhj.swenga2017.plavent#27]
**EXPECTED**
Hosts sees all statistic/information of ROLE GUEST for him as well (HOST requireds role GUEST too)

1. Host sees of all active happening (owner = host) amount of guests, tasks, start, end 
2. Host sees Chart of amount of tasks per happening (Balkendiagramm)
3. Host sees Chart of closed/active Happenings (Tortendiagramm

**Comment by sweiland** [comment]
As described by Mr Heider in 7235fcc we decided to postpone implementation of any charts, as that would likely ruin a lot of things
