### ISSUE TITLE
1.1.1.15 As a guest, I want to see an overview of all events in the dashboard page after login.

### ISSUE THREAD

**Issue by hoedlale16** [sweiland/fhj.swenga2017.plavent#28]
**EXPECTED**
1. Guest see List of all happenings wich start in the future and where guest is currently not registered as guest 
2.) Guest sees a Chart or amount of assigned tasks per happening (happening & Amount of assigned tasks)

**Comment by sweiland** [comment]
ad 1: does it make sense to show a guest all events they aren't invited to?
