### ISSUE TITLE
Passwordreset not working

### ISSUE THREAD

**Issue by heiderst16** [sweiland/fhj.swenga2017.plavent#57]
**OBSERVED**
Password reset mail isn't sent (likely due to submissionbutton misconfiguration).

**EXPECTED**
A password reset mail should be sent.

**STEPS TO REPRODUCE**
1. Arrive at login page.
2. Click "forgot password"
3. input username and click "reset password"
4. nothing happens

**Comment by hoedlale16** [comment]
Fixed with
https://github.com/sweiland/fhj.swenga2017.plavent/commit/e60af96214d95d78e77df3e2d57d12dac5882946
